In [5]:
import numpy as np

In [6]:
# Creating an array
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# Creating a 0-D array
arrzero = np.array(80)

In [8]:
# Checking dimension of an array
print(arrzero.ndim)
arr.ndim

0


1

In [9]:
# Creating 2-D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [10]:
# Number of elements
print(arr.size)
print(arrzero.size)
print(arr2.size)

7
1
10


In [11]:
# Total memory taken by an array
print(arr.nbytes)
print(arrzero.nbytes)
print(arr2.nbytes)

28
4
40


In [12]:
# Single element size
print(arr.itemsize)
print(arrzero.itemsize)
print(arr2.itemsize)

4
4
4


In [13]:
# For data type of the array
print(arr.dtype)
print(arrzero.dtype)
print(arr2.dtype)

int32
int32
int32


In [20]:

# The syntax arr2[0,4] is using a tuple (0,4) to index into the array arr2. The first number 0 is the index of the row, and the second number 4 is the index of the column. So, this line of code is getting the element at the first row and fifth column of the array arr2.

# This line of code prints the elements from index 1 to 2 (exclusive) of the array arr.
print(arr[1:3])

# This line of code retrieves the specific element at the first row and fifth column of the array arr2.
print(arr2[0,4])

# This line of code retrieves the entire second row of the array arr2.
print(arr2[1,:])

# This line of code retrieves all rows starting from the second row of the array arr2.
print(arr2[1:])

# This line of code retrieves the first 5 rows of the array arr2.
print(arr2[:5])

# This line of code retrieves the elements from index 1 to 3 (exclusive) of the second row of the array arr.
print(arr2[1, 1:4])



[2 3]
5
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
