In [89]:
import numpy as np

In [90]:
# Creating an array
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
# Creating a 0-D array
arrzero = np.array(80)

In [92]:
# Checking dimension of an array
print(arrzero.ndim)
arr.ndim

0


1

In [93]:
# Creating 2-D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [94]:
# Number of elements
print(arr.size)
print(arrzero.size)
print(arr2.size)

7
1
10


In [95]:
# Total memory taken by an array
print(arr.nbytes)
print(arrzero.nbytes)
print(arr2.nbytes)

28
4
40


In [96]:
# Single element size
print(arr.itemsize)
print(arrzero.itemsize)
print(arr2.itemsize)

4
4
4


In [97]:
# For data type of the array
print(arr.dtype)
print(arrzero.dtype)
print(arr2.dtype)

int32
int32
int32


In [98]:

# The syntax arr2[0,4] is using a tuple (0,4) to index into the array arr2. The first number 0 is the index of the row, and the second number 4 is the index of the column. So, this line of code is getting the element at the first row and fifth column of the array arr2.

# This line of code prints the elements from index 1 to 2 (exclusive) of the array arr.
print(arr[1:3])

# This line of code retrieves the specific element at the first row and fifth column of the array arr2.
print(arr2[0,4])

# This line of code retrieves the entire second row of the array arr2.
print(arr2[1,:])

# This line of code retrieves all rows starting from the second row of the array arr2.
print(arr2[1:])

# This line of code retrieves the first 5 rows of the array arr2.
print(arr2[:5])

# This line of code retrieves the elements from index 1 to 3 (exclusive) of the second row of the array arr.
print(arr2[1, 1:4])



[2 3]
5
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [99]:
# Copying an array

arr3 = arr.copy()
print(arr3)

[1 2 3 4 5 6 7]


In [100]:
# Zero Matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
# Ones Matrix

np.ones((6,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [102]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
# Other Matrix
np.full((14,4), 32)

array([[32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32]])

In [104]:
# Importing Random
from numpy import random

In [105]:
x= random.randint(10)
print(x)


9


In [106]:
np.random.rand(4,4)

array([[0.64737644, 0.4956687 , 0.30543178, 0.23854766],
       [0.20997301, 0.70868471, 0.47418732, 0.46236217],
       [0.73170071, 0.73128176, 0.96048564, 0.05449907],
       [0.51622897, 0.7141311 , 0.64801096, 0.67313509]])

In [107]:
# Mathematical Operations on array

nums = np.array([10,20,30,40])
print(nums)

[10 20 30 40]


In [108]:
# Addition
nums = nums + 10
print(nums)

[20 30 40 50]


In [109]:
# Subtraction
nums = nums - 10
print(nums)

[10 20 30 40]


In [110]:
# Multiplication 
print(nums)
print(nums*2)

[10 20 30 40]
[20 40 60 80]


In [111]:
# Division
print(nums)
print(nums/4)
print(nums//2)

[10 20 30 40]
[ 2.5  5.   7.5 10. ]
[ 5 10 15 20]


In [112]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([1,2,3,4,5,6])

print(array1+ array2)

[ 2  4  6  8 10 12]


In [113]:
# COS function in array
np.cos(array1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [114]:
# Minimum value in the array
print(np.min(array1))

# Maximum value in the array
print(np.max(array1))

# Sum of all elements
print(np.sum(array1))

1
6
21


In [ ]:
# iterating in 1-D array
for x in array1:
    print(x)

In [118]:
# Iterating in 2-D array
for y in arr2:
    print(y)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [124]:
for z in arr2:
    for b in z:
        print(b)

1
2
3
4
5
6
7
8
9
10
